version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: testProject
      MYSQL_USER: root
      MYSQL_PASSWORD: test1234
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: